### ISSUE TITLE
How to find the operation of C++ functions respect to python?

### ISSUE THREAD

**Issue by mjjdick** [warmspringwinds/pytorch-cpp#21]
Hi, your work is great, and recently, I need to deploy the unet in C++, and I want to use pytorch model directly in C++. So ,I need write a C++ operation of ConvTranspose2d. I noticed that you write the operation of Conv2d, use the functions SpatialDilatedConvolution_updateOutput. so ,if I want to use ConvTranspose2d, which functions can I use, and how can i found them or are there any docs?
Thx very much!!

**Comment by walktree** [comment]
Maybe you could try to export the model to script model, then load it in c++. check here: https://pytorch.org/tutorials/advanced/cpp_export.html

**Comment by mjjdick** [comment]
@walktree thx for your reply, it seems to be a new module in pytorch1.0, I will try~!
